---
name: Wosbee-Admin
version: 0.01
author:
  - 'Henrik Ahlgren <pablo@seestieto.pl>'
abstract: Manage your Wosbee shop with ease
license: perl
build_requires:
  HTML::TableExtract: 0
  LWP::UserAgent: 0
  Test::More: 0
  Text::CSV::Encoded: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Wosbee::Admin:
    file: lib/Wosbee/Admin.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
